### ISSUE TITLE
Delete button to remove a Fish information

### ISSUE THREAD

**Issue by TimNguyen21** [my-fly-box/my-fly-box-ui#25] opened 2020-07-16 19:58 UTC
There should be a Delete Button to remove Fish from User's Fish Caught database and UI. After the delete, the user should return to Fish Caught Page.

**Comment by rachael-t** [comment] 2020-07-21 20:55
Closing this issue as it is a duplicate of #16 and will be handled under the delete fish user story (#5)

**Closed by rachael-t** 2020-07-21 20:55 UTC
Labels: chore, fish caught epic
